### ISSUE TITLE
Could we just pull the list of env vars from the directory (or the brick)?

### ISSUE THREAD

**Issue by ChristopherTracey** [NYNatHeritage/Regional_SDM#32]
In the create model step, could we perhaps read in the list of env vars into a vector directly?  This way, we wouldn't have to modify the code each time we add/subtract new variables?

```
colList <- c("sname","eo_id_st","pres","stratum", "ra",
  "canopy1", "canopy10", "canopy100", "dnwifemw", "dnwiffw", "dnwisemw", "gddays",
  "geo001", "geo002", "geo003", "geo031", "geo032", "geo033", "geo100", "geo200", "geo300",
  "geo400", "geo500", "geo600", "geo700", "impsur1", "impsur10", "impsur100",
  "nlcdfor1", "nlcdfor10", "nlcdfor100", "nlcdopn1", "nlcdopn10", "nlcdopn100",
  "nlcdshb1", "nlcdshb10", "nlcdshb100", "nlcdwat1", "nlcdwat10", "nlcdwat100",
  "nlcdwet1", "nlcdwet10", "nlcdwet100"
    )
```

Then, provided we're setup to keep the first five variables from our species polygons the same, we could change this line `indVarCols <- c(6:43)` to get the max value in the list.

Just a thought for the long term improvement of the method.

**Comment by tghoward** [comment]
yes, we could, but that then puts the onus on us to make sure we have only the envars we want in the folder. Creating this list manually seemed like a good double check, but I think I agree it is unnecessary.

**Comment by tghoward** [comment]
done! Woohoo!  Needs some testing. See commit https://github.com/NYNatHeritage/Regional_SDM/commit/dd89cb3fe3410a7f865203af73ed71c8c38b1627

**Comment by ChristopherTracey** [comment]
Cool! I will try to test next week!
