### ISSUE TITLE
map in the metadata?

### ISSUE THREAD

**Issue by ChristopherTracey** [NYNatHeritage/Regional_SDM#33]
Include a quick preview map of the model in the metadata?  It would be pretty cool! Could it be done?

**Comment by tghoward** [comment]
Good idea. I think it could be done. We would need to think about what we want displayed (e.g. the entire range? Just above a certain threshold?). We would also need to include some reference information (such as state boundaries), but I don't think that's a big deal.

**Comment by ChristopherTracey** [comment]
Yes, I was thinking a fairly simple map with state boundaries and some other basemap information. As far as the model, it would probably be too much to include all values, so we would have to pick some sort of threshold, but something that represents the spatial extent of where predictions were made.

Could we also have the map automatically pan and scale to the extent of the model?

**Comment by tghoward** [comment]
I've got a rudimentary one in there. Need to try it for the entire study area and then clean it up.

**Comment by tghoward** [comment]
https://github.com/NYNatHeritage/Regional_SDM/pull/39/commits/4ddc14789cd007662863a8206f9c06b283e877ea
