### ISSUE TITLE
Regional_SDM/3_createModel.R  change geotiffs to nativeR

### ISSUE THREAD

**Issue by ChristopherTracey** [NYNatHeritage/Regional_SDM#36]
regarding line 21, I think 

`pathToRas <- "D:/RegionalSDM/env_vars/geotiffs"`

needs to be

`pathToRas <- "D:/RegionalSDM/env_vars/nativeR"`

as it causes raslist in line 50 to be empty, which then causes a failure to load any env var names into the dataframes.

**Comment by tghoward** [comment]
fixed:  462eee0eb9007d189a70a316b9d4b56844bdaf4d
