### ISSUE TITLE
non-standard RA value causes

### ISSUE THREAD

**Issue by ChristopherTracey** [NYNatHeritage/Regional_SDM#95]
In the "1_pointsInPolys_cleanBkgPts.R" script, if the input polygons have a value in the RA field that is non-standard (i.e. not 'high', 'medium', etc), it breaks the script when it assigns the random points around line 122. Polygons after this don't get points assigned to them.

It took a little while for me to track the issue down--might be good to have the script check the RA values to make sure no stray values are present.

**Comment by tghoward** [comment]
Good catch, thanks for pointing this out. I'll see what I can do.

**Comment by tghoward** [comment]
Done. See:
https://github.com/NYNatHeritage/Regional_SDM/pull/96
Additional testing to make sure it behaves correctly would be great. Thanks. 
T

**Comment by ChristopherTracey** [comment]
I tested it and it seems to catch the issue.  Thanks!
